### ISSUE TITLE
Add some useful rules to yara

### ISSUE THREAD

**Issue by radare** [radareorg/radare2-extras#12]
It would be nice to be able to have rules for:
- hostnames
- ipv4 and ipv6
- credit-card numbers
- emails

for credit cards we should cook some regexes compatible with libmagic from this: http://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm

Moved from https://github.com/radare/radare2/issues/1139

**Comment by Vlurk** [comment]
In regards to credit card... There should also be a small validation that the number is indeed, "valid" according to the mathematical formula described here: http://www.freeformatter.com/credit-card-number-generator-validator.html

Else, the rule is going to fire so often (in corporate environments at least) that nobody will seriously consider using it.  The false positive rate will be too high.

**Comment by sylvainpelissier** [comment]
r2yara has its own repository now.
