### ISSUE TITLE
A bug?

### ISSUE THREAD

**Issue by rootkiter** [radareorg/radare2-extras#127]
It seems a bug in Makefile ... The command log:
```
radare2-extras-1.6.0$ make all
for a in  ; do \
	( cd $a ; ./configure --prefix=/usr ; make ) ; \
	done
```
yes, `make all` doesn't work...

By the way, The documentation is out of date. 
I can't successfully install through the documentation.
Are you ready to update?
link:https://rada.re/r/down.html

**Comment by radare** [comment]
I dont think you want to install all. But i dont see any error in this issue. You should use r2pm to instal stuff from this repo

Which documwntation are you talking about?

**Comment by rootkiter** [comment]
Typically, a lot of compilation logs are generated after the make command.However, the log above is generated directly, and no other results are output. I mean the output like `gcc -c xxx xxx.c`.At the same time, the command is done in a flash.It's too unreasonable.


The link mentioned above is the document I'm talking about.
For example, the `cd yara/yara3` command is obviously wrong. This directory is not available in the new version of the code.(link:https://rada.re/r/down.html)

**Comment by radare** [comment]
this “document” is the webpage and yes its old, i just fixed it right now
