### ISSUE TITLE
r2snowman: snowman fork outdated/broken

### ISSUE THREAD

**Issue by biot** [radareorg/radare2-extras#174]
`r2pm -i r2snow` build is broken:
[...]
At least one of these targets is not a STATIC_LIBRARY.  Cyclic dependencies are allowed only among static libraries.

This is a known and fixed bug in https://github.com/yegord/snowman/ (see commit 393ccfdd4b99c1a899da8e2c0411ed8f6b89bccb), but the Makefile in r2snowman clones from @fabianfreyer 's fork, which is very outdated and does not include that fix.

**Comment by fabianfreyer** [comment]
While it's not really a solution, I'll try to update it later this evening or tomorrow.

**Comment by trufae** [comment]
Snowman was renamed to smartedec and the project looks abandoned. Closing here
