### ISSUE TITLE
Update the lua plugin and  support lua 5.2 and 5.4

### ISSUE THREAD

**Issue by radare** [radareorg/radare2-extras#202]
$ r2pm  -i r2-lua53

Maybe  use asm.cpu field to specify the version of lua we want to use, not sure if there are many  differences

```
                               ^ ~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~
bin_lua53.c:340:3: error: field designator 'load' does not refer to any field in type 'RBinPlugin'
      (aka 'struct r_bin_plugin_t')
        .load = &load,
         ^
```

<img width="807" alt="Screenshot 2019-08-21 at 12 27 41" src="https://user-images.githubusercontent.com/917142/63424591-1527e380-c40f-11e9-8210-85fbc489dc2b.png">

**Comment by trufae** [comment]
Done too
