### ISSUE TITLE
External RCore plugins commands are not autocompleted

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2-extras#203]
Install YARA plugin first:
```
r2pm install yara
r2pm install r2-yara
```
Then open the radare2 instance:
```
r2 /bin/ls
[0x0000000]>
```
Then start typing `yar` and press TAB - it doesn't autocomplete, while the embedded commands would be autocompleted in this case. While typing `yara?` will still show everything loaded fine.

**Comment by XVilka** [comment]
@ret2libc to consider this for the new shell parser

**Comment by sylvainpelissier** [comment]
This has been solved in the new repository: https://github.com/radareorg/r2yara
