### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by roopeshiitd** [radareorg/radare2-extras#223]
**Getting the below error:**
Please install r2
Makefile:43: recipe for target 'r2' failed
make: *** [r2] Error 1

**Seems to be failing at this line**
R2_PLUGDIR=$(shell r2 -H R2_USER_PLUGINS)
ifeq ($(R2_PLUGDIR),)
r2:
	@echo Please install r2
	@exit 1
endif

I have installed radare2 and its working fine 
r2 -v **outputs** as below
radare2 2.3.0 0 @ linux-x86-64 git.2.3.0
commit: HEAD build: 2018-02-23__17:22:33

**Comment by radare** [comment]
having r2 2.3 is the same as not having r2 installed at all.

please use r2 4.x at least

**Comment by roopeshiitd** [comment]
Thanks a lot. The issue is resolved.
