### ISSUE TITLE
Problem with installing unicorn plugin

### ISSUE THREAD

**Issue by fr0ster** [radareorg/radare2-extras#240]
I can't install unicorn plugin by r2pm

I use radare2 that build from source and use r2pm for installing plugins.
I'me trying install unicorn and get error message ""
I use radare2 with commit ad17ab6d811483e951a4c8b5b89534bd397dc082
I have next installed plugins:
1. keystone
2. keystone-lib
3. r2frida
4. r2ghidra-dec
5. r2lldb
6. sdb
7. unicorn-lib

After command r2pm -i unicorn get message
Final report:
 - PREFIX = /home/alex/.local/share/radare2/prefix
make: Entering directory '/home/alex/.local/share/radare2/r2pm/git/radare2-extras/unicorn'
make -C ../libr/debug clean
make[1]: Entering directory '/home/alex/.local/share/radare2/r2pm/git/radare2-extras/libr/debug'
make -C p clean
make[2]: Entering directory '/home/alex/.local/share/radare2/r2pm/git/radare2-extras/libr/debug/p'
rm -f *.so *.o debug_evm.o debug_unicorn.o
make[2]: Leaving directory '/home/alex/.local/share/radare2/r2pm/git/radare2-extras/libr/debug/p'
make[1]: Leaving directory '/home/alex/.local/share/radare2/r2pm/git/radare2-extras/libr/debug'
make: Leaving directory '/home/alex/.local/share/radare2/r2pm/git/radare2-extras/unicorn'
make: Entering directory '/home/alex/.local/share/radare2/r2pm/git/radare2-extras/unicorn'
make -C ../libr/debug unicorn
make[1]: Entering directory '/home/alex/.local/share/radare2/r2pm/git/radare2-extras/libr/debug'
make -C p debug_unicorn.so
make[2]: Entering directory '/home/alex/.local/share/radare2/r2pm/git/radare2-extras/libr/debug/p'
gcc -I/home/alex/.local/share/radare2/prefix/include -I/usr/local/include/libr -g -I/shlr -I../../include -I../arch/ -I../arch/include -Wall -shared -fPIC  -DLIL_ENDIAN=1 -I/usr/local/include/libr -g -DHAVE_PKGCFG_UNICORN=1 -I/home/alex/.local/share/radare2/prefix/include   -c -o debug_unicorn.o debug_unicorn.c
In file included from /home/alex/.local/share/radare2/prefix/include/sdb/sdbht.h:4,
                 from /home/alex/.local/share/radare2/prefix/include/sdb/sdb.h:14,
                 from /usr/local/include/libr/sdb.h:1,
                 from /usr/local/include/libr/r_list.h:6,
                 from /usr/local/include/libr/r_io.h:6,
                 from /usr/local/include/libr/r_anal.h:11,
                 from /usr/local/include/libr/r_debug.h:5,
                 from debug_unicorn.c:11:
/home/alex/.local/share/radare2/prefix/include/sdb/ht_pp.h:9:10: fatal error: ht_inc.h: No such file or directory
 #include "ht_inc.h"
          ^~~~~~~~~~
compilation terminated.
make[2]: *** [<builtin>: debug_unicorn.o] Error 1
make[2]: Leaving directory '/home/alex/.local/share/radare2/r2pm/git/radare2-extras/libr/debug/p'
make[1]: *** [Makefile:5: unicorn] Error 2
make[1]: Leaving directory '/home/alex/.local/share/radare2/r2pm/git/radare2-extras/libr/debug'
make: *** [Makefile:2: all] Error 2
make: Leaving directory '/home/alex/.local/share/radare2/r2pm/git/radare2-extras/unicorn'

While I don't know how deal with it

**Screenshots**

**Additional context**

**Comment by radare** [comment]
this plugins hasnt been maintained in years so its probably not building with last r2, few fixes should be needed to make it work again, if you are in the mood :) otherwise ill try to find some spare time for it

**Comment by radare** [comment]
fixed
