### ISSUE TITLE
Yara plugin is not build and tested in CI

### ISSUE THREAD

**Issue by sylvainpelissier** [radareorg/radare2-extras#276]
## Environment

CI

## Description
If yara is added in the current ci.yml build, the following error happens:
``` sh
/usr/bin/r2pm: 10: /usr/bin/r2pm: bootstrap.sh: not found
/usr/bin/r2pm: 12: /usr/bin/r2pm: ./configure: not found
``` 
## Test
See https://github.com/sylvainpelissier/radare2-extras/runs/1854501271

**Comment by trufae** [comment]
Maybe $SHELL is not set in the CI? let me do a try

**Comment by trufae** [comment]
https://github.com/radareorg/radare2-pm/commit/c0de19caff81d154a2ad8c7548bf4594f4a18b70 try again

**Comment by sylvainpelissier** [comment]
> Maybe $SHELL is not set in the CI? let me do a try

Yes it is defined to **/bin/bash**.

**Comment by sylvainpelissier** [comment]
> [radareorg/radare2-pm@c0de19c](https://github.com/radareorg/radare2-pm/commit/c0de19caff81d154a2ad8c7548bf4594f4a18b70) try again

Thanks this solved the problem.

**Comment by trufae** [comment]
Yay!
