### ISSUE TITLE
SWF plugin make radare2 crash at start-up

### ISSUE THREAD

**Issue by sylvainpelissier** [radareorg/radare2-extras#292]
## Description

```sh
Mi 08 Sep 2021 08:53:09 CEST
radare2 5.4.0 27076 @ linux-x86-64 git.5.4.0-git
commit: 8d44558224fcce733d443a730de9556f9fe0d861 build: 2021-09-03__16:00:57
Linux x86_64
```

SWF plugin installation make radare2 crash. To reproduce:

```
$ r2pm -i swf
...
$ r2 -
Segmentation fault (core dumped)
```
 Current fix is to uninstall swf.

**Comment by trufae** [comment]
Can you post a backtrace?

**Comment by sylvainpelissier** [comment]
[log.txt](https://github.com/radareorg/radare2-extras/files/7129666/log.txt)

**Comment by sylvainpelissier** [comment]
[log_sanitize.txt](https://github.com/radareorg/radare2-extras/files/7130360/log_sanitize.txt)

**Comment by trufae** [comment]
Fixed
