### ISSUE TITLE
Upgrade python2 scripts to python3

### ISSUE THREAD

**Issue by createyourpersonalaccount** [radareorg/radare2-extras#321]
## Description

I would like all mentions of python to be python3 in radare2. Is this a good idea? I stumbled upon this issue on a fresh install of Debian unstable, when I ran `r2pm install r2dec`. There was an error about python not found, and upon further inspection I've realized that a lot of radare relies on python2 scripts and has plenty of lines such as

    #1/usr/bin/env python

which I believe would be better replaced with the explicit `python3`, and the source code of the scripts converted for that version of python.

[Python2 reached EOL in January of 2020](https://www.python.org/doc/sunset-python-2/), and shouldn't be used any more.

I can try to undertake this task, but no promises! It might be too much. I'm just inquiring if there's any interest before I even attempt it.

**Comment by trufae** [comment]
Already done long time ago

**Comment by createyourpersonalaccount** [comment]
@trufae for example https://github.com/radareorg/radare2-extras/blob/d9273fc53e5a4f796ea3251ac74a4e739bb6c3fc/r2ida/ida2r2/ida2r2.py#L1 mentions `python`, not `python3`. In my opinion, not completed.

**Comment by trufae** [comment]
Last time i used this script was about 15 years ago and i dont have plans to use ida anytime soon. Probably this script needs more things to be updated than just switching to python3.

So i would appreciate if anyone using ida could do this, i think there was another ticket specific for that, but i was refering to r2dec, the r2papi, the bindings, lang and so on.

is there anything else i missed?

**Comment by createyourpersonalaccount** [comment]
@trufae I haven't checked. When I created the issue I was willing to look into things but it's been a long time since and I'm doing other things now.
