### ISSUE TITLE
r2svd line break in SVD files gives errors

### ISSUE THREAD

**Issue by AlexanderKrampe** [radareorg/radare2-extras#322]
## Description
r2svd fails at recognizing line breaks in svd files (for example for the Syncronous and asynchronous receiver). 
In the correspdonig svd file there is a line break at this description. If you remove the line break the error is gone. 

![parsing_svd](https://user-images.githubusercontent.com/38127951/210621844-70d9164a-f277-4897-907c-cfcb9fa44aa5.png)

**Comment by trufae** [comment]
Can you provide a reproducer or a fix? The code is quite small and easy to hack

**Comment by AlexanderKrampe** [comment]
I think r2svd should also set memory maps with 'om' and name them with 'omn' so that we have a complete memory map from the svd file. At the moment only flags or comments are added but no memory maps. 

To reproduce just load blink.bin  [https://github.com/ghidraninja/arm-bare-metal-1/raw/master/blink.bin](url) into r2 (r2 -w -n -m 0x08000000 blink.bin)  and run r2svd

**Comment by trufae** [comment]
Yes that can be done but i would donthe maps when using a specific flag not by default

feel free to send a pr adapting it to your needs the code of r2svd is very easy to modify and tweak
