### ISSUE TITLE
Some pfbs are invalid

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2-extras#372]
<img width="1166" alt="Screenshot 2024-10-30 at 11 05 43" src="https://github.com/user-attachments/assets/650200ea-d5dc-4e81-ac54-535b9a99aa8c">

cc @brainstorm

**Comment by brainstorm** [comment]
Cannot repro, did you fix it already?

<img width="626" alt="Screenshot 2024-10-31 at 10 44 12 am" src="https://github.com/user-attachments/assets/1e950456-4857-4b98-9efd-1eee826b2a48">

**Comment by trufae** [comment]
Not fixed but your output is missing the 1b… maybe its undefined behaviour

**Comment by trufae** [comment]
Fixed now
